version: "3.1"

services:
  liquibase:
    container_name: liquibase
    image: liquibase/liquibase:4.31
    command: update
    environment: 
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/db
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.xml
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: password
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/liquibase/changelog
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: db
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 1s
      timeout: 3s
      retries: 30