services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    hostname: openssh-server # optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=true # optional
      - PASSWORD_ACCESS=true # optional
      - USER_PASSWORD=password # optional
      - USER_NAME=linuxserver # optional
      - LOG_STDOUT= # optional
    volumes:
      - sftphttpdsharedvol:/app
    ports:
      - "22:2222"
    restart: unless-stopped

  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - sftphttpdsharedvol:/usr/local/apache2/htdocs
    restart: unless-stopped

volumes:
  sftphttpdsharedvol: