services:
  mysqldb:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    #expose:
      #- '3306'
    volumes:
      - mysqldbvol:/var/lib/mysql
volumes:
  mysqldbvol: